Week7
CSCI 2461-71
February 25, 2018 

Becoming a Software Engineer by Bill Langenberg

To be a Software Engineer you should have brilliant a computer skill such as to know computer language, problem solves, fast typing, and well algorithms. Software engineer are responsible for developing, designing, testing, writing, modifying, and debugging software based off specific requirements. It can be a flexible position, with contracting and freelancing opportunities commonly available. Companies might bring you on short-term to solve an immediate issue or create a specific program. And also dealing with software requires very structured thinking, since problems can arise from the smallest of errors. It can also require patience and thinking outside the box in order to solve problems with software.  You should have well knowledge core programming language that means to become familiar with programming languages and different operating systems. Examples  C++, Java, Linux, and Python.
Basic knowledge: it’s good opportunity, to learn about to becoming a software Engineer. Is not easy to be software Engineer at list you have basic knowledge like, to manage code and maintaining software to use get these are significant qualities to know so your awareness rises to top. 
 Basic Security:  Always, we use computer software to perform everyday tasks. These can range from sending e-mail, balancing your checkbook, web browsing, shopping and much more. Most people don't stop to think about the security of the software that we use on a daily basis. Users are more concerned about getting their work done, and security is little more than an afterthought.
Engineers vs. Developers:  Software Engineer is more than just programming. It’s a chance to help other people through the power of technology. Having this as a job gives engineers the power to influence other peoples life through programs that could help them with day to day tasks. Software Engineering is an expanding occupation, which means that more and more jobs are opening up for this position everyday. Also, one of the perks of this job is how much money you make. Software Engineering is a good job because, the market is expanding for it, it pays well, and this job can help other people.
Software Developers developers are creative and often natural problem solvers. They possess the ability to think outside the box and have the technical expertise to carry out innovative ideas. In an interview with Ajit Subramani, a software engineer in a major computer firm, he revealed what he believes to be important personal characteristics of a successful developer. Well-developed analytical skills are a must, according to Subramani. ‘You must be able to analyze a situation from all angles to develop an innovative solution’ (Subramani). Analytical skills also come into play when you look past the basic requirements of a program or design, and dig deeper to understand how the program will be used in daily life. ‘To be effective, software engineers also need strong communication skills’ (Subramani). Although the job does involve extreme concentration and chunks of uninterrupted time, software developers often have to collaborate with others, including fellow developers, management or clients.
Finally, it is essential article. It’s help me to know the key to became become software and work with computer.  I personally learn a lot form this article such as, Linux, choose the right tools for the job, core computer science skills and basic security. I was not have any to be software Engineer before, but know I’m thinking who know, if I work hard I will be one of them. 



